import fs from "node:fs";
import vm from "node:vm";

const dataFiles=["js/02-campaign-solo-data.js","js/03-campaign-duo-data.js","js/03b-campaign-trio-data.js","js/03c-campaign-endgame-data.js","js/03d-endgame-mechanics.js"];
const context={window:{WD_LANG_PACKS:{en:{exact:{},patterns:[]}}}};
vm.createContext(context);
const prelude=`const REAL_ABILITY_IDS=[1,2,3,4,5,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25];const START_HP=25;const BOSS_PHASES={};const ACHIEVEMENTS={};`;
const localization=fs.readFileSync("lang/en-campaign.js","utf8");
const expose=`result={worlds:[...CAMPAIGN_WORLDS,...DUO_CAMPAIGN_WORLDS,...TRIO_CAMPAIGN_WORLDS],encounters:[...CAMPAIGN_ENCOUNTERS,...DUO_CAMPAIGN_ENCOUNTERS,...TRIO_CAMPAIGN_ENCOUNTERS],phases:BOSS_PHASES,mutators:ELITE_MUTATORS,profiles:ENEMY_AI_PROFILES,modifiers:ENCOUNTER_MODIFIERS,rules:ENDGAME_WORLD_RULES,ruleHandlers:WORLD_RULE_RUNTIME_HANDLERS,modifierHandlers:ENCOUNTER_MODIFIER_RUNTIME_HANDLERS,mutatorHandlers:ELITE_MUTATOR_RUNTIME_HANDLERS,phaseCrossings:bossPhaseThresholdsCrossed,translations:window.WD_LANG_PACKS.en.exact};`;
vm.runInContext(localization+prelude+dataFiles.map(file=>fs.readFileSync(file,"utf8")).join("\n")+expose,context,{filename:"campaign-validation.bundle.js"});
const {worlds,encounters,phases,mutators,profiles,modifiers,rules,ruleHandlers,modifierHandlers,mutatorHandlers,phaseCrossings,translations}=context.result;
const validAbilityIds=new Set([1,2,3,4,5,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]);
const errors=[],ids=new Set(),worldIds=new Set(worlds.map(w=>w.id));
const endgameWorldIds=new Set(["astral","void","eclipse","bloodmoon","prism","singularity"]),ruleIds=new Set(Object.values(rules).map(rule=>rule.id));
const playerIdPattern=/\b(?:duo|trio)_[a-z0-9_]+\b/i,germanHint=/[äöüß]|\b(?:der|die|das|den|und|mit|muss|Gewinne|Verursache|Spieler|Welt|Nach|Heilt|Gegner|Held|Zug|Angriff|Fähigkeit|Schaden)\b/i;
const visibleValues=value=>{const values=[];const skip=new Set(["id","world","prefix","requires","firstRequires","unlockRequires","finalEncounterId","definitionId","instanceId","enemyInstanceId","enemyDefinitionId","ability","secondAbility","thirdAbility","type","role","aiProfile","mutator","modifier","worldRule"]);const walk=v=>{if(typeof v==="string")values.push(v);else if(Array.isArray(v))v.forEach(walk);else if(v&&typeof v==="object")Object.entries(v).filter(([key])=>!skip.has(key)).forEach(([,child])=>walk(child));};walk(value);return values;};
const challengeRules=challenge=>!challenge?[]:challenge.type==="all"?(challenge.rules||[]).flatMap(challengeRules):[challenge];
const assertTranslation=(value,where)=>{if(typeof value==="string"&&value.trim()&&germanHint.test(value)&&!translations[value])errors.push(`missing EN localization: ${where} -> ${value}`);};

for(const encounter of encounters){
  if(ids.has(encounter.id))errors.push(`duplicate encounter id: ${encounter.id}`);ids.add(encounter.id);
  const fallback=encounter.id.startsWith("trio_")?"trinity":encounter.id.startsWith("duo_")?"covenant":"house";
  if(!worldIds.has(encounter.world||fallback))errors.push(`invalid world: ${encounter.id} -> ${encounter.world}`);
  if(!Array.isArray(encounter.enemies)||!encounter.enemies.length)errors.push(`missing enemies: ${encounter.id}`);
  const tags=encounter.tags||[];if(new Set(tags).size!==tags.length)errors.push(`duplicate encounter tags: ${encounter.id}`);
  const instanceIds=[];
  for(const [enemyIndex,enemy] of (encounter.enemies||[]).entries()){
    for(const key of ["ability","secondAbility","thirdAbility"]){const value=enemy[key];if(value!=null&&value!=="mirror"&&!validAbilityIds.has(Number(value))&&Number(value)!==0)errors.push(`invalid ${key}: ${encounter.id}/${enemy.name}/${value}`);}
    if(enemy.aiProfile&&!profiles[enemy.aiProfile])errors.push(`invalid AI profile: ${encounter.id}/${enemy.name}/${enemy.aiProfile}`);
    if(enemy.mutator&&!mutators[enemy.mutator])errors.push(`invalid mutator: ${encounter.id}/${enemy.name}/${enemy.mutator}`);
    if(!enemy.definitionId)errors.push(`missing enemy definition id: ${encounter.id}/${enemy.name}`);
    if(enemy.definitionId&&!/^[a-z0-9_:-]+$/.test(enemy.definitionId))errors.push(`invalid enemy definition id: ${encounter.id}/${enemy.definitionId}`);
    const instanceId=enemy.enemyInstanceId||enemy.instanceId||`${encounter.id}:${enemyIndex}`;if(instanceIds.includes(instanceId))errors.push(`duplicate enemyInstanceId: ${encounter.id}/${instanceId}`);instanceIds.push(instanceId);
  }
  if(encounter.modifier&&!modifiers[encounter.modifier])errors.push(`invalid modifier: ${encounter.id}/${encounter.modifier}`);
  if(encounter.modifier&&!modifierHandlers[encounter.modifier])errors.push(`modifier without runtime handler: ${encounter.id}/${encounter.modifier}`);
  if(encounter.worldRuleActive&&(!encounter.worldRule||!ruleIds.has(encounter.worldRule)))errors.push(`missing worldRule definition: ${encounter.id}/${encounter.worldRule}`);
  if(encounter.worldRuleActive&&!ruleHandlers[encounter.worldRule])errors.push(`worldRule without runtime handler: ${encounter.id}/${encounter.worldRule}`);
  for(const requirement of encounter.requires||[])if(!encounters.some(e=>e.id===requirement))errors.push(`missing unlock: ${encounter.id} -> ${requirement}`);
  if(encounter.isBoss&&!phases[encounter.id])errors.push(`boss without phase: ${encounter.id}`);
  if(phases[encounter.id]&&!encounter.enemies.some(e=>e.name===phases[encounter.id].boss))errors.push(`phase boss reference: ${encounter.id}/${phases[encounter.id].boss}`);
  for(const rule of challengeRules(encounter.challenge))if(["ability_use","ability_success","each_hero_ability_use","each_hero_ability_success"].includes(rule.type)&&!validAbilityIds.has(Number(rule.ability)))errors.push(`objective has invalid required ability: ${encounter.id}/${rule.ability}`);
  if(endgameWorldIds.has(encounter.world)){[encounter.title,encounter.subtitle,encounter.desc,encounter.challenge?.text].forEach(value=>assertTranslation(value,encounter.id));for(const text of visibleValues(encounter))if(playerIdPattern.test(text))errors.push(`internal ID in player-facing encounter text: ${encounter.id}/${text}`);}
}
for(const [id,definition] of Object.entries(phases)){const list=Array.isArray(definition.phases)?definition.phases:[definition],thresholds=list.map(p=>Number(p.threshold));if(thresholds.some(v=>!Number.isFinite(v)||v<=0||v>=1))errors.push(`invalid phase threshold: ${id}`);if(new Set(thresholds).size!==thresholds.length)errors.push(`duplicate phase threshold: ${id}`);if(thresholds.some((v,index)=>index>0&&thresholds[index-1]<=v))errors.push(`unsorted phase thresholds: ${id}`);}
for(const world of worlds){if(world.finalEncounterId&&!ids.has(world.finalEncounterId))errors.push(`missing world boss: ${world.id}/${world.finalEncounterId}`);if(world.worldRule&&!rules[world.id])errors.push(`invalid world rule: ${world.id}`);if(endgameWorldIds.has(world.id)){[world.name,world.desc,world.lockedText].forEach(value=>assertTranslation(value,`world ${world.id}`));for(const text of visibleValues(world))if(playerIdPattern.test(text))errors.push(`internal ID in player-facing world text: ${world.id}/${text}`);}}
for(const id of Object.keys(mutators))if(!mutatorHandlers[id])errors.push(`mutator without runtime handler: ${id}`);for(const id of Object.keys(modifiers))if(!modifierHandlers[id])errors.push(`modifier without runtime handler: ${id}`);for(const id of ruleIds)if(!ruleHandlers[id])errors.push(`worldRule without runtime handler: ${id}`);for(const [de,en] of Object.entries(translations))if(!de||!en)errors.push(`empty localization pair: ${de}`);

const mechanicsSource=fs.readFileSync("js/03d-endgame-mechanics.js","utf8");
for(const id of ruleIds)if(!mechanicsSource.includes(`rule===\"${id}\"`)&&!mechanicsSource.includes(`rule===\'${id}\'`))errors.push(`worldRule handler is metadata-only: ${id}`);
Object.assign(context,{campaignMode:true,players:[],encounterRuntime:{},TEST_ENCOUNTER:null,queueEventPopup(){},addLog(){},renderEncounterRuleBanner(){},playerAbilities(index){const p=context.players[index]||{};return[p.ability,p.secondAbility,p.thirdAbility].filter(x=>x!=null);},campaignHeroIndices(){return context.players.map((p,i)=>p?.campaignTeam==="hero"?i:null).filter(i=>i!=null);},currentEncounterObject(){return context.TEST_ENCOUNTER;}});
const call=source=>vm.runInContext(source,context);
const resetRule=(id,heroes=[{campaignTeam:"hero",hp:10,maxHp:10,ability:1}])=>{context.players=heroes;context.TEST_ENCOUNTER={worldRuleActive:true,worldRule:id};context.encounterRuntime={phaseRuleIds:[],markedHero:null,markTurns:0,markSource:null,lastLightUsed:new Set(),arcaneUsed:new Set(),worldMomentum:{},enemyTurnCount:0,escalationLevel:0,precisionUsed:new Set(),pendingOneShotDamage:{}};};
resetRule("hunters_mark",[{campaignTeam:"hero",hp:8,maxHp:10},{campaignTeam:"hero",hp:3,maxHp:10}]);call("applyWorldRuleOnEncounterStart()");if(context.encounterRuntime.markedHero!==1||context.encounterRuntime.markTurns!==2)errors.push("hunters_mark runtime matrix failed");
resetRule("last_light",[{campaignTeam:"hero",hp:3,maxHp:10}]);if(call("worldRuleDamageBonus(0,5)")!==2)errors.push("last_light bonus calculation failed");call("commitOneShotDamageBonuses(0,0)");if(context.encounterRuntime.lastLightUsed.has("0")||call("worldRuleDamageBonus(0,5)")!==2)errors.push("last_light zero-damage consumption failed");call("commitOneShotDamageBonuses(0,1)");if(!context.encounterRuntime.lastLightUsed.has("0")||call("worldRuleDamageBonus(0,5)")!==0)errors.push("last_light successful consumption failed");
resetRule("momentum_war");call("applyWorldRuleAfterAttack(0,4)");if(call("worldRuleDamageBonus(0,4)")!==1)errors.push("momentum_war build failed");call("applyWorldRuleAfterAttack(0,0)");if(call("worldRuleDamageBonus(0,4)")!==0)errors.push("momentum_war reset failed");
resetRule("blood_moon");call("applyWorldRuleOnEncounterStart()");if(!context.encounterRuntime.phaseRuleIds.includes("blood_moon"))errors.push("blood_moon bridge failed");
resetRule("arcane_instability",[{campaignTeam:"hero",hp:10,maxHp:10,ability:18}]);if(call("worldRuleDamageBonus(0,5)")!==1)errors.push("arcane_instability bonus calculation failed");call("commitOneShotDamageBonuses(0,0)");if(context.encounterRuntime.arcaneUsed.has("0")||call("worldRuleDamageBonus(0,5)")!==1)errors.push("arcane_instability zero-damage consumption failed");call("commitOneShotDamageBonuses(0,1)");if(!context.encounterRuntime.arcaneUsed.has("0")||call("worldRuleDamageBonus(0,5)")!==0)errors.push("arcane_instability successful consumption failed");
resetRule("final_gravity");context.players.push({campaignTeam:"enemy",hp:10,maxHp:10});context.encounterRuntime.enemyTurnCount=4;call("applyWorldRuleOnEnemyTurn()");if(context.encounterRuntime.escalationLevel!==1)errors.push("final_gravity runtime matrix failed");
const resetModifier=(id,player={campaignTeam:"hero",hp:10,maxHp:10,voluntaryHpPaidThisTurn:false})=>{context.players=[player];context.TEST_ENCOUNTER={modifier:id};context.encounterRuntime={phaseRuleIds:[],precisionUsed:new Set(),lastLightUsed:new Set(),arcaneUsed:new Set(),pendingOneShotDamage:{},worldMomentum:{},enemyTurnCount:0,escalationLevel:0,markedHero:null,markTurns:0,markSource:null};};
resetModifier("precision_trial");if(call("campaignOutgoingDamageModifier(0,5)")!==1)errors.push("precision_trial bonus calculation failed");call("commitOneShotDamageBonuses(0,0)");if(context.encounterRuntime.precisionUsed.has("0")||call("campaignOutgoingDamageModifier(0,5)")!==1)errors.push("precision_trial zero-damage consumption failed");call("commitOneShotDamageBonuses(0,1)");if(!context.encounterRuntime.precisionUsed.has("0")||call("campaignOutgoingDamageModifier(0,5)")!==0)errors.push("precision_trial successful consumption failed");
resetModifier("glass_cannon");if(call("campaignOutgoingDamageModifier(0,5)")!==2)errors.push("glass_cannon runtime failed");
resetModifier("blood_debt",{campaignTeam:"hero",hp:10,maxHp:10,voluntaryHpPaidThisTurn:true});if(call("campaignOutgoingDamageModifier(0,5)")!==1)errors.push("blood_debt runtime failed");
resetModifier("last_breath",{campaignTeam:"hero",hp:2,maxHp:10});if(call("campaignOutgoingDamageModifier(0,5)")!==1)errors.push("last_breath runtime failed");
resetModifier("hunted",{campaignTeam:"hero",hp:10,maxHp:10});if(call("chooseHuntedHero(()=>.75)")!==0)errors.push("hunted single-hero selection failed");call("initializeEncounterMechanics()");if(context.encounterRuntime.markedHero!==0||context.encounterRuntime.markSource!=="hunted")errors.push("hunted solo initialization failed");
resetModifier("hunted");context.players=[{campaignTeam:"hero",hp:10,maxHp:10},{campaignTeam:"hero",hp:10,maxHp:10}];if(call("chooseHuntedHero(()=>0)")!==0||call("chooseHuntedHero(()=>.99)")!==1)errors.push("hunted duo selection is fixed to player 1");
context.players=[{campaignTeam:"hero",hp:0,maxHp:10},{campaignTeam:"hero",hp:10,maxHp:10},{campaignTeam:"hero",hp:10,maxHp:10}];if(call("chooseHuntedHero(()=>0)")!==1||call("chooseHuntedHero(()=>.99)")!==2)errors.push("hunted selected a dead hero");
resetModifier("rapid_escalation");context.encounterRuntime.enemyTurnCount=7;call("updateEncounterEscalation()");if(context.encounterRuntime.escalationLevel!==2)errors.push("rapid_escalation runtime failed");
if(!fs.readFileSync("js/12-battle-ui.js","utf8").includes('modifier==="no_recovery"'))errors.push("no_recovery has no healing runtime hook");
const twinInstances=call('[0,1].map(i=>buildCampaignEnemyPlayer({name:"Twin",definitionId:"twin",hp:10,ability:1},{id:"validator_twins"},i).enemyInstanceId)');if(new Set(twinInstances).size!==2)errors.push("identical enemy definitions collide at runtime");
const battleUiSource=fs.readFileSync("js/12-battle-ui.js","utf8");if(!battleUiSource.includes("aliveHeroes.includes(encounterRuntime.markedHero)")||!battleUiSource.includes('encounterRuntime.markSource==="hunted"'))errors.push("hunted mark is not wired into normal enemy targeting");if(!battleUiSource.includes("players.forEach((p,i)=>")||!battleUiSource.includes("el.dataset.instanceId=p.enemyInstanceId"))errors.push("enemy rendering is not instance-bound");if(!battleUiSource.includes("encounterRuntime.markSource=null"))errors.push("expired marks do not clear ownership");
if(/modifier===\"hunted\"[^}]*heroes\[0\]/s.test(mechanicsSource))errors.push("hunted still hardcodes heroes[0]");
const campaignSource=fs.readFileSync("js/06-campaign.js","utf8");if(!campaignSource.includes('markSource="boss_phase"')||!campaignSource.includes("pendingOneShotDamage:{}"))errors.push("boss mark ownership or encounter cleanup regression");
const battleActionsSource=fs.readFileSync("js/13-battle-actions.js","utf8"),commitCalls=[...battleActionsSource.matchAll(/commitOneShotDamageBonuses\(current,actualDamage\)/g)];if(commitCalls.length!==1||!/const actualDamage=mainResult\.lost;\s*commitOneShotDamageBonuses\(current,actualDamage\)/.test(battleActionsSource))errors.push("one-shot damage bonuses are not committed exactly once after main actualDamage");
const phaseCases=[
  {from:80,to:60,triggered:[],want:[0]},{from:80,to:30,triggered:[],want:[0,1]},{from:80,to:10,triggered:[],want:[0,1]},
  {from:40,to:20,triggered:[0],want:[1]},{from:40,to:0,triggered:[0],want:[1]},{from:70,to:0,triggered:[],want:[0,1]}
];
for(const test of phaseCases){const got=phaseCrossings([{threshold:.66},{threshold:.33}],test.triggered,test.from,test.to,100);if(JSON.stringify(got)!==JSON.stringify(test.want))errors.push(`boss phase stress ${test.from}->${test.to}: got [${got}], expected [${test.want}]`);}

const fingerprint=encounter=>JSON.stringify({count:encounter.enemies.length,roles:encounter.enemies.map(e=>e.role).sort(),objective:challengeRules(encounter.challenge).map(r=>r.type).sort(),required:challengeRules(encounter.challenge).map(r=>r.ability).filter(Boolean).sort(),modifier:encounter.modifier||null,mutators:encounter.enemies.map(e=>e.mutator||null),rule:encounter.worldRule||null,tags:encounter.tags||[]});
const compareWorlds=(a,b)=>{const left=encounters.filter(e=>e.world===a),right=encounters.filter(e=>e.world===b),same=left.filter((e,i)=>right[i]&&fingerprint(e)===fingerprint(right[i])).length;if(same>4)errors.push(`content diversity regression: ${a}/${b} share ${same}/15 positional fingerprints`);return same;};
const duoSame=compareWorlds("eclipse","bloodmoon"),trioSame=compareWorlds("prism","singularity");

const rushSource=fs.readFileSync("js/37-duo-boss-rush.js","utf8"),rushStageSource=rushSource.split("const STAGES=Object.freeze([")[1]?.split("]);")[0]||"";
const rushIds=[...rushStageSource.matchAll(/encounterId:"([^"]+)"/g)].map(match=>match[1]);if(rushIds.length!==10)errors.push(`Boss Rush requires 10 stages, found ${rushIds.length}`);if(new Set(rushIds).size!==rushIds.length)errors.push("duplicate Boss Rush encounter id");rushIds.forEach(id=>{if(!ids.has(id))errors.push(`Boss Rush missing encounter: ${id}`)});
const rushStages=vm.runInNewContext(`[${rushStageSource}]`),rushHp=rushStages.map(stage=>stage.enemies.reduce((sum,enemy)=>sum+enemy.hp,0));if(rushHp.at(-1)<=rushHp[0])errors.push("Boss Rush final HP pressure does not exceed stage 1");if(rushStages.some(stage=>stage.enemies.length>3))errors.push("Boss Rush stage exceeds supported enemy UI count");if(!rushSource.includes("run=null;")||!rushSource.includes("rewardHistory:[]")||!rushSource.includes("perks:{}"))errors.push("Boss Rush run reset/default state hooks missing");if(!rushSource.includes("thirdAbility=abilityId")||rushSource.includes("fourthAbility=abilityId"))errors.push("Boss Rush ability cap/replacement regression");
const rewardSource=rushSource.split("const REWARDS=Object.freeze([")[1]?.split("]);")[0]||"";for(const match of rewardSource.matchAll(/(?:name|desc):"([^"]+)"/g))assertTranslation(match[1],"Boss Rush reward");for(const match of rushSource.matchAll(/\.textContent\s*=\s*"([^"]+)"/g))if(germanHint.test(match[1]))errors.push(`hardcoded Boss Rush UI string without tr(): ${match[1]}`);
if(errors.length){console.error(errors.map(x=>`- ${x}`).join("\n"));process.exit(1);}
const endgame=encounters.filter(e=>endgameWorldIds.has(e.world));console.log(`Endgame validated: ${endgame.length} encounters, ${Object.keys(profiles).length} AI profiles, ${Object.keys(mutators).length} mutators, ${Object.keys(modifiers).length} modifiers, ${ruleIds.size} world rules, ${rushIds.length} Boss Rush stages (HP ${rushHp.join("/")}), ${Object.keys(translations).length} static DE/EN pairs; positional fingerprints equal duo=${duoSame}/15, trio=${trioSame}/15.`);
